language: swift
osx_image: xcode10
script:
    - xcodebuild clean test -project RelativeView.xcodeproj -scheme RelativeView -destination "platform=iOS Simulator,name=iPhone 7,OS=12.0" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
